### PR TITLE
Add default size mark to Gtk.Scale

### PR DESCRIPTION
**Pull request by vanillajonathan**
This adds a mark for the default size (43).

### CODE REVIEW

**Comment by d-go** [comment]
Hi!,thanks for contributing, I'll merge this PR and push the new version in Gnome shell extensions later today.

**Comment by vanillajonathan** [comment]
@d-go You forgot?

**Comment by d-go** [comment]
Hi, @vanillajonathan , sorry for the delay, I've been busy these days and hadn't had chance to release your changes, I just merged your PR and fixed [this issue](https://github.com/d-go/quick-settings-avatar/issues/4). also submitted the new version in gnome-shell extensions, it'll be published in some hours probably.
Let me know if your change appears once you get the new version installed.
And thanks again for contributing :D

**Comment by vanillajonathan** [comment]
Thanks, it is published and the changes appears and works.

**Pull request merged**
